# questions_level3.py
# Level 3: Command Confidence (Typing)
# Note: Current engine.py checks typing answers with exact match.
# Future enhancement: allow multiple acceptable answers / flexible matching.

level3_questions = [
    {
        'type': 'type',
        'question': 'Type the command to show your current working directory.',
        'options': [],
        'answer': 'pwd',
        'answer_text': 'pwd',
        'explanation': 'pwd prints the full path of your current directory.',
        'why': 'You need this constantly when navigating in the terminal.',
    },
    {
        'type': 'type',
        'question': 'Type the command to list files in the current directory.',
        'options': [],
        'answer': 'ls',
        'answer_text': 'ls',
        'explanation': 'ls lists directory contents.',
        'why': 'Basic navigation skill.',
    },
    {
        'type': 'type',
        'question': 'Type the command to list files with details (permissions, owner, size).',
        'options': [],
        'answer': 'ls -l',
        'answer_text': 'ls -l',
        'explanation': '-l is the long listing format.',
        'why': 'Helps troubleshoot permissions and file info.',
    },
    {
        'type': 'type',
        'question': 'Type the command to list ALL files including hidden ones, with details.',
        'options': [],
        'answer': 'ls -la',
        'answer_text': 'ls -la',
        'explanation': '-a includes hidden files; -l shows details.',
        'why': 'Hidden config files are everywhere on Linux.',
    },
    {
        'type': 'type',
        'question': 'Type the command to change into your home directory.',
        'options': [],
        'answer': 'cd ~',
        'answer_text': 'cd ~',
        'explanation': '~ expands to your home directory.',
        'why': 'Quick way to return home from anywhere.',
    },
    {
        'type': 'type',
        'question': 'Type the command to go up one directory level.',
        'options': [],
        'answer': 'cd ..',
        'answer_text': 'cd ..',
        'explanation': '.. means the parent directory.',
        'why': 'Fast navigation without typing full paths.',
    },
    {
        'type': 'type',
        'question': "Type the command to create a directory named 'test'.",
        'options': [],
        'answer': 'mkdir test',
        'answer_text': 'mkdir test',
        'explanation': 'mkdir creates directories.',
        'why': 'Creating folders is basic organization.',
    },
    {
        'type': 'type',
        'question': "Type the command to remove a file named 'old.txt'.",
        'options': [],
        'answer': 'rm old.txt',
        'answer_text': 'rm old.txt',
        'explanation': 'rm removes files.',
        'why': 'Knowing safe deletion commands matters.',
    },
    {
        'type': 'type',
        'question': "Type the command to remove a directory named 'test' and everything inside it.",
        'options': [],
        'answer': 'rm -r test',
        'answer_text': 'rm -r test',
        'explanation': '-r means recursive, so it removes folder contents too.',
        'why': 'This is powerful—helps you understand why to be careful.',
    },
    {
        'type': 'type',
        'question': "Type the command to copy file 'a.txt' to 'b.txt'.",
        'options': [],
        'answer': 'cp a.txt b.txt',
        'answer_text': 'cp a.txt b.txt',
        'explanation': 'cp copies files.',
        'why': 'Copying is common for backups and experiments.',
    },
    {
        'type': 'type',
        'question': "Type the command to move/rename 'a.txt' to 'b.txt'.",
        'options': [],
        'answer': 'mv a.txt b.txt',
        'answer_text': 'mv a.txt b.txt',
        'explanation': 'mv moves or renames files depending on the destination.',
        'why': 'Renaming is a daily task.',
    },
    {
        'type': 'type',
        'question': "Type the command to show the contents of a file named 'notes.txt'.",
        'options': [],
        'answer': 'cat notes.txt',
        'answer_text': 'cat notes.txt',
        'explanation': 'cat prints file contents to the terminal.',
        'why': 'Quickly viewing text files is a core skill.',
    },
    {
        'type': 'type',
        'question': "Type the command to view a file named 'biglog.txt' with scrolling (pager).",
        'options': [],
        'answer': 'less biglog.txt',
        'answer_text': 'less biglog.txt',
        'explanation': 'less lets you scroll and search through output.',
        'why': 'Makes large files readable.',
    },
    {
        'type': 'type',
        'question': "Type the command to show the first 20 lines of 'file.txt'.",
        'options': [],
        'answer': 'head -n 20 file.txt',
        'answer_text': 'head -n 20 file.txt',
        'explanation': 'head prints the beginning of a file; -n sets line count.',
        'why': 'Quick checks without opening an editor.',
    },
    {
        'type': 'type',
        'question': "Type the command to show the last 50 lines of 'app.log'.",
        'options': [],
        'answer': 'tail -n 50 app.log',
        'answer_text': 'tail -n 50 app.log',
        'explanation': 'tail prints the end of a file; -n sets line count.',
        'why': 'Log troubleshooting usually starts at the bottom.',
    },
    {
        'type': 'type',
        'question': "Type the command to follow a log file named 'syslog' live (keep updating).",
        'options': [],
        'answer': 'tail -f syslog',
        'answer_text': 'tail -f syslog',
        'explanation': '-f follows the file as it grows.',
        'why': 'Live log watching is a superpower for debugging.',
    },
    {
        'type': 'type',
        'question': "Type the command to search for the word 'ERROR' inside 'app.log'.",
        'options': [],
        'answer': 'grep ERROR app.log',
        'answer_text': 'grep ERROR app.log',
        'explanation': 'grep searches for matching lines in a file.',
        'why': 'Finds problems quickly in logs.',
    },
    {
        'type': 'type',
        'question': "Type the command to search recursively for 'Listen' inside files under /etc.",
        'options': [],
        'answer': 'grep -r Listen /etc',
        'answer_text': 'grep -r Listen /etc',
        'explanation': '-r searches directories recursively.',
        'why': 'Helps locate config settings across many files.',
    },
    {
        'type': 'type',
        'question': "Type the command to find all files named 'hosts' under /etc.",
        'options': [],
        'answer': 'find /etc -name hosts',
        'answer_text': 'find /etc -name hosts',
        'explanation': 'find searches directories for names and other attributes.',
        'why': 'Find files even when you don’t know the exact path.',
    },
    {
        'type': 'type',
        'question': 'Type the command to find all .conf files under /etc.',
        'options': [],
        'answer': 'find /etc -name "*.conf"',
        'answer_text': 'find /etc -name "*.conf"',
        'explanation': 'Quotes protect the wildcard so the shell doesn’t expand it early.',
        'why': 'Conf files are common and useful to locate.',
    },
    {
        'type': 'type',
        'question': 'Type the command to show how much disk space is free/used (human-readable).',
        'options': [],
        'answer': 'df -h',
        'answer_text': 'df -h',
        'explanation': 'df shows filesystem usage; -h makes sizes readable.',
        'why': 'First check when you suspect disk space issues.',
    },
    {
        'type': 'type',
        'question': "Type the command to show how much space a folder named 'Downloads' uses.",
        'options': [],
        'answer': 'du -sh Downloads',
        'answer_text': 'du -sh Downloads',
        'explanation': 'du estimates disk usage; -s summary; -h human-readable.',
        'why': 'Find what’s eating your disk.',
    },
    {
        'type': 'type',
        'question': 'Type the command to update package lists on Debian/Ubuntu/Mint.',
        'options': [],
        'answer': 'sudo apt update',
        'answer_text': 'sudo apt update',
        'explanation': 'This refreshes available package information from repositories.',
        'why': 'Needed before installs/upgrades when package lists are stale.',
    },
    {
        'type': 'type',
        'question': 'Type the command to upgrade installed packages on Debian/Ubuntu/Mint.',
        'options': [],
        'answer': 'sudo apt upgrade',
        'answer_text': 'sudo apt upgrade',
        'explanation': 'This upgrades installed packages to newer versions.',
        'why': 'Standard maintenance step.',
    },
    {
        'type': 'type',
        'question': "Type the command to install the package named 'git'.",
        'options': [],
        'answer': 'sudo apt install git',
        'answer_text': 'sudo apt install git',
        'explanation': 'apt installs packages from configured repositories.',
        'why': 'Installing software is a core daily task.',
    },
    {
        'type': 'type',
        'question': "Type the command to search available packages for 'python3'.",
        'options': [],
        'answer': 'apt search python3',
        'answer_text': 'apt search python3',
        'explanation': 'apt search searches package names/descriptions.',
        'why': 'Useful when you don’t know the exact package name.',
    },
    {
        'type': 'type',
        'question': "Type the command to show detailed info about the package 'curl'.",
        'options': [],
        'answer': 'apt show curl',
        'answer_text': 'apt show curl',
        'explanation': 'apt show displays package metadata.',
        'why': 'Helps you verify what you’re installing.',
    },
    {
        'type': 'type',
        'question': "Type the command to remove the package 'nano' (keep config files).",
        'options': [],
        'answer': 'sudo apt remove nano',
        'answer_text': 'sudo apt remove nano',
        'explanation': 'remove uninstalls the package but may keep configs.',
        'why': 'Understanding remove vs purge matters.',
    },
    {
        'type': 'type',
        'question': "Type the command to remove the package 'nano' AND its config files.",
        'options': [],
        'answer': 'sudo apt purge nano',
        'answer_text': 'sudo apt purge nano',
        'explanation': 'purge removes package + configuration files.',
        'why': 'Useful for a totally clean reinstall.',
    },
    {
        'type': 'type',
        'question': 'Type the command to remove unused dependency packages.',
        'options': [],
        'answer': 'sudo apt autoremove',
        'answer_text': 'sudo apt autoremove',
        'explanation': 'Removes dependencies no longer needed by installed packages.',
        'why': 'Keeps your system clean over time.',
    },
    {
        'type': 'type',
        'question': 'Type the command to show your IP addresses and network interfaces.',
        'options': [],
        'answer': 'ip a',
        'answer_text': 'ip a',
        'explanation': 'ip a lists network interfaces and addresses.',
        'why': 'Key step in network troubleshooting.',
    },
    {
        'type': 'type',
        'question': 'Type the command to test connectivity to google.com (simple ping).',
        'options': [],
        'answer': 'ping google.com',
        'answer_text': 'ping google.com',
        'explanation': 'ping tests network reachability (ICMP).',
        'why': 'Quick check for network connectivity.',
    },
    {
        'type': 'type',
        'question': 'Type the command to ping 8.8.8.8 exactly 4 times and stop.',
        'options': [],
        'answer': 'ping -c 4 8.8.8.8',
        'answer_text': 'ping -c 4 8.8.8.8',
        'explanation': '-c sets the count so ping doesn’t run forever.',
        'why': 'Good habit for quick tests.',
    },
    {
        'type': 'type',
        'question': 'Type the command to show running processes in a detailed list.',
        'options': [],
        'answer': 'ps aux',
        'answer_text': 'ps aux',
        'explanation': 'ps aux lists many processes with details.',
        'why': 'Helps find what’s consuming CPU/RAM.',
    },
    {
        'type': 'type',
        'question': 'Type the command to open the interactive process monitor (common tool).',
        'options': [],
        'answer': 'top',
        'answer_text': 'top',
        'explanation': 'top is a built-in interactive process viewer.',
        'why': 'Fast way to see why your system is slow.',
    },
    {
        'type': 'type',
        'question': 'Type the command to stop a process with PID 1234 gracefully (SIGTERM).',
        'options': [],
        'answer': 'kill -15 1234',
        'answer_text': 'kill -15 1234',
        'explanation': 'SIGTERM asks a process to exit cleanly.',
        'why': 'Prefer graceful stops before force-killing.',
    },
    {
        'type': 'type',
        'question': 'Type the command to force-kill a stuck process with PID 1234.',
        'options': [],
        'answer': 'kill -9 1234',
        'answer_text': 'kill -9 1234',
        'explanation': 'SIGKILL immediately stops a process and cannot be ignored.',
        'why': 'Last resort when a process won’t quit.',
    },
    {
        'type': 'type',
        'question': 'Type the command to check the status of the ssh service (systemd).',
        'options': [],
        'answer': 'sudo systemctl status ssh',
        'answer_text': 'sudo systemctl status ssh',
        'explanation': 'systemctl status shows whether a service is running and recent logs.',
        'why': 'Great for diagnosing services that won’t start.',
    },
    {
        'type': 'type',
        'question': 'Type the command to restart the ssh service (systemd).',
        'options': [],
        'answer': 'sudo systemctl restart ssh',
        'answer_text': 'sudo systemctl restart ssh',
        'explanation': 'restart stops then starts a service.',
        'why': 'Common after configuration changes.',
    },
    {
        'type': 'type',
        'question': 'Type the command to view recent system logs with errors (systemd journal).',
        'options': [],
        'answer': 'journalctl -xe',
        'answer_text': 'journalctl -xe',
        'explanation': 'journalctl views logs; -xe shows recent messages with extra context.',
        'why': 'First stop when something fails unexpectedly.',
    },
    {
        'type': 'type',
        'question': 'Type the command to show kernel/hardware messages (useful for USB problems).',
        'options': [],
        'answer': 'dmesg',
        'answer_text': 'dmesg',
        'explanation': 'dmesg shows kernel ring buffer messages.',
        'why': 'Helps debug hardware detection and driver issues.',
    },
    {
        'type': 'type',
        'question': "Type the command to make 'script.sh' executable.",
        'options': [],
        'answer': 'chmod +x script.sh',
        'answer_text': 'chmod +x script.sh',
        'explanation': '+x adds execute permission.',
        'why': 'Very common step when running scripts.',
    },
    {
        'type': 'type',
        'question': "Type the command to run a script named 'script.sh' from the current directory.",
        'options': [],
        'answer': './script.sh',
        'answer_text': './script.sh',
        'explanation': "./ means 'current directory'.",
        'why': 'Explains why you can’t usually run local files without ./',
    },
    {
        'type': 'type',
        'question': "Type the command to show what 'HOME' is set to.",
        'options': [],
        'answer': 'echo $HOME',
        'answer_text': 'echo $HOME',
        'explanation': '$HOME is an environment variable for your home directory.',
        'why': 'Environment variables are used everywhere.',
    },
    {
        'type': 'type',
        'question': 'Type the command to show the PATH environment variable.',
        'options': [],
        'answer': 'echo $PATH',
        'answer_text': 'echo $PATH',
        'explanation': '$PATH lists directories searched for executables.',
        'why': "Explains 'command not found' problems.",
    },
    {
        'type': 'type',
        'question': 'Type the command to print the current username.',
        'options': [],
        'answer': 'whoami',
        'answer_text': 'whoami',
        'explanation': 'whoami prints the effective username.',
        'why': 'Useful when you forget which user you’re operating as.',
    },
    {
        'type': 'type',
        'question': 'Type the command to show the current date and time.',
        'options': [],
        'answer': 'date',
        'answer_text': 'date',
        'explanation': 'date prints the system date/time.',
        'why': 'Helpful for logs, timestamps, and sanity checks.',
    },
    {
        'type': 'type',
        'question': "Type the command to create an empty file named 'newfile.txt'.",
        'options': [],
        'answer': 'touch newfile.txt',
        'answer_text': 'touch newfile.txt',
        'explanation': 'touch creates an empty file (or updates timestamps).',
        'why': 'Handy for quick file creation and build systems.',
    },
    {
        'type': 'type',
        'question': "Type the command to count lines in 'file.txt'.",
        'options': [],
        'answer': 'wc -l file.txt',
        'answer_text': 'wc -l file.txt',
        'explanation': 'wc counts; -l counts lines.',
        'why': 'Quick check for file size/shape.',
    },
    {
        'type': 'type',
        'question': 'Type the command to download a webpage to the terminal using curl.',
        'options': [],
        'answer': 'curl https://example.com',
        'answer_text': 'curl https://example.com',
        'explanation': 'curl fetches content from a URL.',
        'why': 'Useful for testing internet and APIs.',
    },
]
